import { Toaster } from "@/components/ui/toast"
import type { Metadata } from "next";
import localFont from "next/font/local"
import { Geist } from 'next/font/google'
import "./globals.css";
import Footer from "@/components/Footer";
import "../styles/animations.css";

import Nav from "@/components/Nav";

const GTUltra = localFont({
    src: '../assets/fonts/GT-Ultra/GT-Ultra-Fine-Regular-Trial.woff2',
    variable: '--gt-ultra'
});

const PPMori = localFont({
    src: [
        {
            path: '../assets/fonts/PP-Mori/PPMori-Regular.otf',
            weight: '400',
            style: 'normal',
        },
        {
            path: '../assets/fonts/PP-Mori/PPMori-SemiBold.otf',
            weight: '600',
            style: 'normal',
        },
    ],
    variable: '--pp-mori',
});

const geistSans = Geist({
    variable: '--geist',
    subsets: ['latin'],
});

export const metadata: Metadata = {
	title: "Knowescape Consulting · Skills Development · Enterprise & Supplier Development",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
	return (
		<html
			lang="en"
			className={`h-full antialiased ${GTUltra.variable} ${geistSans.variable}  ${PPMori.variable}`}
		>
			<body className={`min-h-full flex flex-col`} >
                <Nav />
                {children}
                <Toaster />
                <Footer />
            </body>
		</html>
	);
}
